{% set name = "nitransforms" %}
{% set version = "25.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nitransforms-{{ version }}.tar.gz
  sha256: 59cb34895fc43422e1b231fa8530e6c6802c34037dab377d9fec166e2034e1a5

build:
  entry_points:
    - nb-transform = nitransforms.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21
    - scipy >=1.8
    - nibabel >=4.0
    - h5py >=3.9

test:
  imports:
    - nitransforms
  commands:
    - pip check
    - nb-transform --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/nipy/nitransforms
  summary: NiTransforms -- Neuroimaging spatial transforms in Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Dhananjhay
